/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildsEditorRouteImport } from './routes/builds-editor'
import { Route as KillersRouteImport } from './routes/killers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SurvivorsRouteImport } from './routes/survivors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsEditorRoute = BuildsEditorRouteImport.update({
  id: '/builds-editor',
  path: '/builds-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const KillersRoute = KillersRouteImport.update({
  id: '/killers',
  path: '/killers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SurvivorsRoute = SurvivorsRouteImport.update({
  id: '/survivors',
  path: '/survivors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builds-editor': typeof BuildsEditorRoute
  '/killers': typeof KillersRoute
  '/login': typeof LoginRoute
  '/survivors': typeof SurvivorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builds-editor': typeof BuildsEditorRoute
  '/killers': typeof KillersRoute
  '/login': typeof LoginRoute
  '/survivors': typeof SurvivorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builds-editor': typeof BuildsEditorRoute
  '/killers': typeof KillersRoute
  '/login': typeof LoginRoute
  '/survivors': typeof SurvivorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/builds-editor' | '/killers' | '/login' | '/survivors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/builds-editor' | '/killers' | '/login' | '/survivors'
  id: '__root__' | '/' | '/builds-editor' | '/killers' | '/login' | '/survivors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildsEditorRoute: typeof BuildsEditorRoute
  KillersRoute: typeof KillersRoute
  LoginRoute: typeof LoginRoute
  SurvivorsRoute: typeof SurvivorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds-editor': {
      id: '/builds-editor'
      path: '/builds-editor'
      fullPath: '/builds-editor'
      preLoaderRoute: typeof BuildsEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/killers': {
      id: '/killers'
      path: '/killers'
      fullPath: '/killers'
      preLoaderRoute: typeof KillersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survivors': {
      id: '/survivors'
      path: '/survivors'
      fullPath: '/survivors'
      preLoaderRoute: typeof SurvivorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildsEditorRoute: BuildsEditorRoute,
  KillersRoute: KillersRoute,
  LoginRoute: LoginRoute,
  SurvivorsRoute: SurvivorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
