/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurvivorsRouteImport } from './routes/survivors'
import { Route as KillersRouteImport } from './routes/killers'
import { Route as BuildCreatorRouteImport } from './routes/buildCreator'
import { Route as IndexRouteImport } from './routes/index'

const SurvivorsRoute = SurvivorsRouteImport.update({
  id: '/survivors',
  path: '/survivors',
  getParentRoute: () => rootRouteImport,
} as any)
const KillersRoute = KillersRouteImport.update({
  id: '/killers',
  path: '/killers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildCreatorRoute = BuildCreatorRouteImport.update({
  id: '/buildCreator',
  path: '/buildCreator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buildCreator': typeof BuildCreatorRoute
  '/killers': typeof KillersRoute
  '/survivors': typeof SurvivorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buildCreator': typeof BuildCreatorRoute
  '/killers': typeof KillersRoute
  '/survivors': typeof SurvivorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buildCreator': typeof BuildCreatorRoute
  '/killers': typeof KillersRoute
  '/survivors': typeof SurvivorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buildCreator' | '/killers' | '/survivors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buildCreator' | '/killers' | '/survivors'
  id: '__root__' | '/' | '/buildCreator' | '/killers' | '/survivors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildCreatorRoute: typeof BuildCreatorRoute
  KillersRoute: typeof KillersRoute
  SurvivorsRoute: typeof SurvivorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/survivors': {
      id: '/survivors'
      path: '/survivors'
      fullPath: '/survivors'
      preLoaderRoute: typeof SurvivorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/killers': {
      id: '/killers'
      path: '/killers'
      fullPath: '/killers'
      preLoaderRoute: typeof KillersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildCreator': {
      id: '/buildCreator'
      path: '/buildCreator'
      fullPath: '/buildCreator'
      preLoaderRoute: typeof BuildCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildCreatorRoute: BuildCreatorRoute,
  KillersRoute: KillersRoute,
  SurvivorsRoute: SurvivorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
